export const APPLIANCES = [
    {
        id: 1, 
        model: 'nam HO-001',
        category: 'hoover',
        producter: 'cleancraft',
        image: 'https://i.pinimg.com/236x/ba/03/e3/ba03e33f34040d663045395a76864d0c.jpg',
        price: 199.99,
        discount: 0,
    },
    {
        id: 2,
        model: '-',
        category: '-',
        producter: '-',
        image: '',
        price: 0,
        discount: 0,
    },
    {
        id: 3,
        model: 'nam ST-003',
        category: 'stove',
        producter: 'royalchef',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKTMENd3ApGHd2hGmOOi_qYykxcxzta0TRvg&s',
        price: 445.00,
        discount: 0.25,
    },
    {
        id: 4,
        model: '-',
        category: '-',
        producter: '-',
        image: '',
        price: 0,
        discount: 0,
    },
    {
        id: 5,
        model: 'nam FR-002',
        category: 'freezer',
        producter: 'freezmaker',
        image: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS1VnXvjTjvnq-TGmTrP2UAMsX7eokBFffsUwgXqoiejaHK7pq_',
        price: 999.00,
        discount: 0.1,
    },
    {
        id: 6,
        model: '-',
        category: '-',
        producter: '-',
        image: '',
        price: 0,
        discount: 0,
    },
]